services:
    Eckinox\BoltNavigationUI\ExtensionMenu:
        class: Eckinox\BoltNavigationUI\ExtensionMenu

    Eckinox\BoltNavigationUI\Utils\Search\NavigationContentSearch:        
        arguments:
            $defaultLocale: '%locale%'
